# Generated by Django 5.0.6 on 2024-06-10 11:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('action', models.CharField(max_length=100)),
                ('frequency', models.DurationField(default=datetime.timedelta(days=1))),
                ('execution_time', models.DurationField()),
                ('is_public', models.BooleanField(default=False)),
                ('is_pleasureful', models.BooleanField(default=False)),
                ('reward', models.CharField(blank=True, max_length=200, null=True)),
                ('connected_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminderer.habit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'habit',
                'verbose_name_plural': 'habits',
            },
        ),
    ]
